/*
   Copyright 2016 Saptarshi Purkayastha

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package edu.iupui.soic.bhi.jpg2dicomtags;

import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author sunbiz
 */
public class MainWindow extends javax.swing.JFrame {

    private int jpgCount;
    private int dcmCount;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        converterFrame = new javax.swing.JFrame();
        dcmFolderLabel1 = new javax.swing.JLabel();
        dcmFolderField1 = new javax.swing.JTextField();
        dcmFolderButton1 = new javax.swing.JButton();
        renameButton = new javax.swing.JButton();
        jpgFolderLabel = new javax.swing.JLabel();
        jpgFolderField = new javax.swing.JTextField();
        jpgFolderButton = new javax.swing.JButton();
        dcmFolderLabel = new javax.swing.JLabel();
        dcmFolderField = new javax.swing.JTextField();
        dcmFolderButton = new javax.swing.JButton();
        jpgFileCountLabel = new javax.swing.JLabel();
        dcmFileCountLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        toolsMenu = new javax.swing.JMenu();
        renamerItem = new javax.swing.JMenuItem();
        aboutItem = new javax.swing.JMenuItem();

        converterFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        converterFrame.setTitle("Rename files to .dcm extension");

        dcmFolderLabel1.setText("Select DCM folder:");

        dcmFolderButton1.setText("Select Folder");
        dcmFolderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcmFolderButton1ActionPerformed(evt);
            }
        });

        renameButton.setText("Rename to .dcm");
        renameButton.setEnabled(false);
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout converterFrameLayout = new javax.swing.GroupLayout(converterFrame.getContentPane());
        converterFrame.getContentPane().setLayout(converterFrameLayout);
        converterFrameLayout.setHorizontalGroup(
            converterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(converterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcmFolderLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcmFolderField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcmFolderButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, converterFrameLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        converterFrameLayout.setVerticalGroup(
            converterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(converterFrameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(converterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dcmFolderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcmFolderField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcmFolderButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purkayastha Lab's JPG to DICOM with Tags");
        setResizable(false);

        jpgFolderLabel.setText("Select JPG folder:");

        jpgFolderButton.setText("Select Folder");
        jpgFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpgFolderButtonActionPerformed(evt);
            }
        });

        dcmFolderLabel.setText("Select DCM folder:");

        dcmFolderButton.setText("Select Folder");
        dcmFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcmFolderButtonActionPerformed(evt);
            }
        });

        jpgFileCountLabel.setForeground(new java.awt.Color(255, 51, 51));
        jpgFileCountLabel.setText("JPGs:");

        dcmFileCountLabel.setForeground(new java.awt.Color(255, 0, 51));
        dcmFileCountLabel.setText("DCMs:");

        convertButton.setText("CONVERT");
        convertButton.setEnabled(false);
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        toolsMenu.setText("File");

        renamerItem.setText("Rename files to DCM");
        renamerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renamerItemActionPerformed(evt);
            }
        });
        toolsMenu.add(renamerItem);

        aboutItem.setText("About");
        toolsMenu.add(aboutItem);

        menuBar.add(toolsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jpgFolderLabel)
                        .addGap(32, 32, 32)
                        .addComponent(jpgFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpgFolderButton)
                        .addGap(18, 18, 18)
                        .addComponent(jpgFileCountLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dcmFolderLabel)
                        .addGap(28, 28, 28)
                        .addComponent(dcmFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dcmFolderButton)
                        .addGap(18, 18, 18)
                        .addComponent(dcmFileCountLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jpgFolderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jpgFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpgFolderButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jpgFileCountLabel)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(dcmFolderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dcmFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcmFolderButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(dcmFileCountLabel)))
                .addGap(12, 12, 12)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpgFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpgFolderButtonActionPerformed

        int result;

        JFileChooser jpgFolderChooser = new JFileChooser();

        jpgFolderChooser.setCurrentDirectory(new java.io.File("."));
        jpgFolderChooser.setDialogTitle("Select JPG Folder");
        jpgFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        jpgFolderChooser.setAcceptAllFileFilterUsed(false);
        if (jpgFolderChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File jpgFolder = jpgFolderChooser.getSelectedFile();
            jpgFolderField.setText(jpgFolder.getAbsolutePath());
            jpgCount = jpgFolder.listFiles(new JpgFilter()).length;
            jpgFileCountLabel.setText(Integer.toString(jpgCount) + " JPGs");
            if (jpgCount == dcmCount && jpgCount != 0) {
                convertButton.setEnabled(true);
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_jpgFolderButtonActionPerformed

    private void dcmFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcmFolderButtonActionPerformed
        int result;

        JFileChooser dcmFolderChooser = new JFileChooser();

        dcmFolderChooser.setCurrentDirectory(new java.io.File("."));
        dcmFolderChooser.setDialogTitle("Select DCM Folder");
        dcmFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        dcmFolderChooser.setAcceptAllFileFilterUsed(false);
        if (dcmFolderChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File dcmFolder = dcmFolderChooser.getSelectedFile();
            dcmFolderField.setText(dcmFolder.getAbsolutePath());
            dcmCount = dcmFolder.listFiles(new DcmFilter()).length;
            dcmFileCountLabel.setText(Integer.toString(dcmCount) + " DCMs");
            if (jpgCount == dcmCount && jpgCount != 0) {
                convertButton.setEnabled(true);
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_dcmFolderButtonActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        boolean success = true;
        File jpgFolder = new File(jpgFolderField.getText());
        File dcmFolder = new File(dcmFolderField.getText());
        if (jpgFolder.isDirectory() && dcmFolder.isDirectory()) {
            File[] jpgFiles = jpgFolder.listFiles(new JpgFilter());
            File[] dcmFiles = dcmFolder.listFiles(new DcmFilter());
            for (int i = 0; i < jpgFiles.length; i++) {
                Runtime rt = Runtime.getRuntime();
                try {
                    System.out.println("EXECUTING..." + "img2dcm.exe \"" + jpgFiles[i].getAbsolutePath() + "\" \"" + jpgFolder.getAbsolutePath() + "\\" + i + ".dcm\" --dataset-from \"" + dcmFiles[i].getAbsolutePath()+"\"");
                    Process pr = rt.exec("img2dcm.exe \"" + jpgFiles[i].getAbsolutePath() + "\" \"" + jpgFolder.getAbsolutePath() + "\\" + i + ".dcm\" --dataset-from \"" + dcmFiles[i].getAbsolutePath()+"\"");
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                    success = false;
                }
            }
            if (success) {
                JOptionPane.showMessageDialog(this, "SUCCESS!!");
            } else {
                JOptionPane.showMessageDialog(this, "FAILURE!!");
            }
        }

    }//GEN-LAST:event_convertButtonActionPerformed

    private void renamerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renamerItemActionPerformed
        converterFrame.setVisible(true);
    }//GEN-LAST:event_renamerItemActionPerformed

    private void dcmFolderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcmFolderButton1ActionPerformed
        JFileChooser dcmFolderChooser = new JFileChooser();

        dcmFolderChooser.setCurrentDirectory(new java.io.File("."));
        dcmFolderChooser.setDialogTitle("Select DCM Folder");
        dcmFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        dcmFolderChooser.setAcceptAllFileFilterUsed(false);
        if (dcmFolderChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File dcmFolder = dcmFolderChooser.getSelectedFile();
            dcmFolderField1.setText(dcmFolder.getAbsolutePath());
            int dcmCount = dcmFolder.listFiles().length;
            if (dcmCount != 0) {
                renameButton.setEnabled(true);
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_dcmFolderButton1ActionPerformed

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        File dcmRenameFolder = new File(dcmFolderField1.getText());
        File[] dcmFiles = dcmRenameFolder.listFiles();
        for (File file : dcmFiles) {
            Path path = file.toPath();
            try {
                Files.move(path, path.resolveSibling(file.getName() + ".dcm"));
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_renameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private class DcmFilter implements FilenameFilter {

        @Override
        public boolean accept(File dir, String name) {
            if (name.lastIndexOf('.') > 0) {
                // get last index for '.' char
                int lastIndex = name.lastIndexOf('.');
                // get extension
                String str = name.substring(lastIndex);
                // match path name extension
                if (str.equals(".dcm")) {
                    return true;
                }
            }
            return false;
        }
    }

    private class JpgFilter implements FilenameFilter {

        @Override
        public boolean accept(File dir, String name) {
            if (name.lastIndexOf('.') > 0) {
                // get last index for '.' char
                int lastIndex = name.lastIndexOf('.');
                // get extension
                String str = name.substring(lastIndex);
                // match path name extension
                if (str.equals(".jpg")) {
                    return true;
                }
            }
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JButton convertButton;
    private javax.swing.JFrame converterFrame;
    private javax.swing.JLabel dcmFileCountLabel;
    private javax.swing.JButton dcmFolderButton;
    private javax.swing.JButton dcmFolderButton1;
    private javax.swing.JTextField dcmFolderField;
    private javax.swing.JTextField dcmFolderField1;
    private javax.swing.JLabel dcmFolderLabel;
    private javax.swing.JLabel dcmFolderLabel1;
    private javax.swing.JLabel jpgFileCountLabel;
    private javax.swing.JButton jpgFolderButton;
    private javax.swing.JTextField jpgFolderField;
    private javax.swing.JLabel jpgFolderLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton renameButton;
    private javax.swing.JMenuItem renamerItem;
    private javax.swing.JMenu toolsMenu;
    // End of variables declaration//GEN-END:variables
}
